{% set name = "libsolv" %}
{% set version = "0.7.13" %}
{% set sha256 = "869985ff4c5a3d8a1544900c26277defec362eea0b85498be5b1d09c3c0e0e62" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/openSUSE/libsolv/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - export_solv_version_win.patch  # [win]
    - enable_subprio_comparison.patch

build:
  number: 3
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake
  host:
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libsolv${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libsolvext${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libsolv.so.1  # [linux]
    - test -f $PREFIX/include/solv/repo.h  # [unix]
    - if exist %LIBRARY_INC%\\solv\\repo.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_INC%\\lib\\solv.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_INC%\\lib\\solvext.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_INC%\\bin\\solv.dll (exit 0) else (exit 1)  # [win]
    - dumpsolv.exe -h  # [win]
    - dumpsolv -h  # [unix]

about:
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
  description: libsolv, a free package dependency solver using a satisfiability algorithm.
  dev_url: https://github.com/openSUSE/libsolv

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - davidbrochart
