{% set name = "libsolv" %}
{% set version = "0.7.4" %}
{% set sha256 = "725b598075c5c44a90cbda5594fd29417144ff8acb9762996162e7b68f94c8c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/openSUSE/libsolv/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - msvc_support.patch
    - cmake_fixes.patch
    - fix_osx_rpath.patch

build:
  number: 0
  skip: True  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libsolv.so  # [linux]
    - test -f $PREFIX/lib/libsolv.so.1  # [linux]
    - test -f $PREFIX/lib/libsolv.dylib  # [osx]
    - test -f $PREFIX/include/solv/repo.h  # [unix]
    - if exist %LIBRARY_INC%\\solv\\repo.h (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/openSUSE/libsolv
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: 'Library for solving packages and reading repositories'
  description: 'libsolv, a free package dependency solver using a satisfiability algorithm.'
  dev_url: https://github.com/openSUSE/libsolv

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
