travis:
  secure:
    BINSTAR_TOKEN: lzSiChtnMzvSuiplwFqn0/S6+1j4eBYW2pvkgqiLBy3wbn22zxtqKUZYWgYMlvb6jgir/m6MjfemLWQHSzbVsNxKy1TfjxYONO9f5uOaGxfAxvnxVazsLb4pa5Vj72054GNfRApjwC2QPlxOvqHsLhbZ8uOKw7bpV9hp7Ue+oELVO+AcW+OcXc8rVn68v8DuRpkmz00V0sau1IF/+46LCVt9LNbiGhTjg3ZizSGzm9W/OwjmwBQXqDEFOOHn9GrAz0MSN6ONHbaMtVYInTi/JkxRQ4naKWU0299DWCaYJDA3LELRa8fmEajZWvVG6vBxuAZwA6RDGBH5vBAbLxQBqq64EzEL3SJKOvUvdxcoZSl3vGRwsZ0fIKDUAipCFcu24l9TpQB8+L8UObWEtK2GJynahAdlQM6Hw3PRTrpgqHccC1nyNP+CtcoL8lADAwGhXfm8koJWarQ5/CFvRndIlEGzzj3TpcBBtIBmmj8m1EnmFJV4vfqS6AqifoIzMplxzt+08ABwBykXHWpvXQcbszh1+6eqLtie0EFTqWQOY9OaDVgO3/2mkoLiK5LqJfALOIwvJYuxMIplOOMeCqYL+MAVAYX5SGMq0U9osCwbCYchHEtO0HBbtfsWtux3WYeVKNX4gGWsWXq6QWZ8hgjEcqilY6eyiCxy9DwjIVYZXuQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
